version: '3.4'

services:

  postgresql:
    image: postgres:15.0-alpine
    container_name: 'postgresql'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'testdb'
    ports:
      - '5432:5432'
    restart: always

