version: '3.4'

services:

  postgresql:
    image: postgres:15.0-alpine
    container_name: 'postgresql'
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'testdb'
    ports:
      - '5432:5432'
    restart: always

  # rabbitmq:
  #   image: rabbitmq:3.11.1-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:15672"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
